version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: uvicorn src.main:app --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - redis_db
    volumes:
      - ./:/workspace/boardy_test
    networks:
      - app-network

  redis_db:
    image: redis/redis-stack:latest
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


